### ISSUE TITLE
Taranis x9D+: ui.lua - not enough memory

### ISSUE THREAD

**Issue by RipperDrone** [papayou66/betaflight-tx-lua-scripts#1]
Seems like the lua script is getting more spacy, got this error message. Have 20 models defined - maybe too much for bulky lua scripts? Or is there another reason that this error message is thrown?

OpenTX 2.2.1 installed...

**Comment by papayou66** [comment]
I just finish all my test in X9 and QX7 i do not have error.
2.2.0 and 2.2.1 tested
what is the exact message ?

**Comment by papayou66** [comment]
I will upload the script now in ZIP files

**Comment by papayou66** [comment]
@RipperDrone 
https://github.com/papayou66/betaflight-tx-lua-scripts/releases/download/v1.0.2K/V1.0.2K.zip
copy SCRIPTS folder in your SD cart

**Comment by RipperDrone** [comment]
message is ike in title. I tried some more things out: Despite my 20+ models, Taranis says ~7624byte free, so this seems ok. I built the firmwares with different switches: -lua, -luac, both of them, and the new font.

It seems like building the firmware with -luac only, the memory error message is gone. (??) Building with -lua or both (and always new font), memory message is thrown.

**Comment by RipperDrone** [comment]
I have installed the script from /src directory of release, just copied it into root of Taranis SD card.

**Comment by papayou66** [comment]
Yes correction is on the way

**Comment by RipperDrone** [comment]
it always came after scrolling past the Kalman page - it would not return to 'page 1' of telemetry...

**Comment by RipperDrone** [comment]
Great! 

So with the correction: What is the best switch config for firmware: -lua -luac - sql5font...?

**Comment by papayou66** [comment]
lua

**Comment by RipperDrone** [comment]
ok, thx

**Comment by papayou66** [comment]
Correction is upload

**Comment by papayou66** [comment]
https://github.com/papayou66/betaflight-tx-lua-scripts/releases/download/v1.0.2K/V1.0.2K.zip
